import 'package:banay/localization/banay_localization_home_keys.dart';

const Map<String, Map<String, String>> banayHomeLocalizedValues = {
  'mg': {
    BanayHomeLocalizationKeys.defaultStoreName: 'Boutique BANAY',
    BanayHomeLocalizationKeys.liveUnavailable: 'Tsy misy intsony io live io.',
    BanayHomeLocalizationKeys.followedTitle: 'Ireo arahinao',
    BanayHomeLocalizationKeys.followedEmptyTitle: 'Tsy mbola misy arahina',
    BanayHomeLocalizationKeys.followedEmptyMessage:
        'Araho ireo boutique na olona mba hahitanao azy ireo eto.',
    BanayHomeLocalizationKeys.notificationsTooltip: 'Sokafy ny notifications',
    BanayHomeLocalizationKeys.livekitConfigIncomplete:
        'Tsy feno ny fikirakirana LiveKit ao amin\'ny serveur.',
    BanayHomeLocalizationKeys.cannotStartLive:
        'Tsy afaka manomboka live izao aloha.',
    BanayHomeLocalizationKeys.liveDefaultTitle: '{name} mivantana',
    BanayHomeLocalizationKeys.liveDefaultCategory: 'Fampisehoana produit',
    BanayHomeLocalizationKeys.createLiveTitle: 'Hamorona live',
    BanayHomeLocalizationKeys.createLiveSubtitle:
        'Omano ny direct-nao ary asehoy avy hatrany.',
    BanayHomeLocalizationKeys.liveTitleHint: 'Lohatenin\'ny live',
    BanayHomeLocalizationKeys.liveCategoryHint: 'Lohahevitra na categorie',
    BanayHomeLocalizationKeys.liveTitleRequired:
        'Ampio lohateny vao afaka mandefa live.',
    BanayHomeLocalizationKeys.liveCategoryRequired:
        'Ampio categorie vao afaka mandefa live.',
    BanayHomeLocalizationKeys.launchLive: 'Alefa ny live',
    BanayHomeLocalizationKeys.startLive: 'Hanomboka live',
    BanayHomeLocalizationKeys.noMoreProducts: 'Tsy misy produit hafa',
    BanayHomeLocalizationKeys.followedMemberFallback: 'Mpikambana BANAY',
    BanayHomeLocalizationKeys.followedSubtitleFallback: 'Arahi-maso',
    BanayHomeLocalizationKeys.followedSellerBadge: 'Boutique',
    BanayHomeLocalizationKeys.followedProfileBadge: 'Profil',
    BanayHomeLocalizationKeys.followedLiveNow: 'Mivantana izao',
    BanayHomeLocalizationKeys.followedViewLive: 'Hijery live',
    BanayHomeLocalizationKeys.followedViewProfile: 'Hijery profil',
    BanayHomeLocalizationKeys.storiesCreateLabel: 'Hamorona story',
    BanayHomeLocalizationKeys.storiesYourStory: 'Ny story-nao',
    BanayHomeLocalizationKeys.storyCreateTitle: 'Story vaovao',
    BanayHomeLocalizationKeys.storyCreateSubtitle:
        'Zarao amin\'ny mpifandray aminao ny sary na video mandritra ny 24 ora.',
    BanayHomeLocalizationKeys.storyPickGallery: 'Hisafidy sary',
    BanayHomeLocalizationKeys.storyPickGallerySubtitle:
        'Avy amin\'ny galerie-nao',
    BanayHomeLocalizationKeys.storyPickCamera: 'Haka sary',
    BanayHomeLocalizationKeys.storyPickCameraSubtitle: 'Amin\'ny fakan-tsary',
    BanayHomeLocalizationKeys.storyCaptionHint: 'Ampio soratra…',
    BanayHomeLocalizationKeys.storyPublishAction: 'Alefa ny story',
    BanayHomeLocalizationKeys.storyPublished: 'Lasa ny story-nao.',
    BanayHomeLocalizationKeys.storyPublishFailed: 'Tsy afaka mandefa ny story.',
    BanayHomeLocalizationKeys.storyImagePickFailed: 'Tsy afaka naka ny sary.',
    BanayHomeLocalizationKeys.storyDeleteAction: 'Fafao',
    BanayHomeLocalizationKeys.storyDeleteConfirmTitle:
        'Hofafana ve ity story ity ?',
    BanayHomeLocalizationKeys.storyDeleteConfirmBody:
        'Tsy ho hitan\'ny mpanaraka anao intsony izy.',
    BanayHomeLocalizationKeys.storyDeleted: 'Voafafa ny story.',
    BanayHomeLocalizationKeys.storyDeleteFailed: 'Tsy afaka namafa ny story.',
    BanayHomeLocalizationKeys.storyViewersTitle: 'Nahita ny story',
    BanayHomeLocalizationKeys.storyNoViewersYet:
        'Mbola tsy nisy nahita ity story ity.',
    BanayHomeLocalizationKeys.storyUnavailable:
        'Tsy misy intsony ity story ity.',
    BanayHomeLocalizationKeys.storyJustNow: 'Vao izao',
    BanayHomeLocalizationKeys.storyMinutesAgo: '{count} min lasa',
    BanayHomeLocalizationKeys.storyHoursAgo: '{count} ora lasa',
    BanayHomeLocalizationKeys.storyPickVideoGallery: 'Hisafidy video',
    BanayHomeLocalizationKeys.storyPickVideoCamera: 'Haka video',
    BanayHomeLocalizationKeys.storyVideoTooLong:
        'Tsy tokony hihoatra ny {seconds} segondra ny video.',
    BanayHomeLocalizationKeys.storyVideoTooLarge:
        'Tsy tokony hihoatra ny {size} Mo ny video.',
    BanayHomeLocalizationKeys.storyVideoPreviewFailed:
        'Tsy afaka mamaky ity video ity.',
    BanayHomeLocalizationKeys.storyUploading: 'Mandefa ny story…',
    BanayHomeLocalizationKeys.storyFinalizing: 'Eo am-pamaranana…',
  },
  'en': {
    BanayHomeLocalizationKeys.defaultStoreName: 'BANAY Shop',
    BanayHomeLocalizationKeys.liveUnavailable:
        'This live is no longer available.',
    BanayHomeLocalizationKeys.followedTitle: 'Following',
    BanayHomeLocalizationKeys.followedEmptyTitle: 'No subscriptions yet',
    BanayHomeLocalizationKeys.followedEmptyMessage:
        'Follow shops or people to find them here.',
    BanayHomeLocalizationKeys.notificationsTooltip: 'Open notifications',
    BanayHomeLocalizationKeys.livekitConfigIncomplete:
        'The server LiveKit configuration is incomplete.',
    BanayHomeLocalizationKeys.cannotStartLive:
        'Unable to start the live right now.',
    BanayHomeLocalizationKeys.liveDefaultTitle: '{name} live now',
    BanayHomeLocalizationKeys.liveDefaultCategory: 'Product showcase',
    BanayHomeLocalizationKeys.createLiveTitle: 'Create a live',
    BanayHomeLocalizationKeys.createLiveSubtitle:
        'Prepare your live and make it visible right away.',
    BanayHomeLocalizationKeys.liveTitleHint: 'Live title',
    BanayHomeLocalizationKeys.liveCategoryHint: 'Theme or category',
    BanayHomeLocalizationKeys.liveTitleRequired:
        'Add a title to start the live.',
    BanayHomeLocalizationKeys.liveCategoryRequired:
        'Add a category to start the live.',
    BanayHomeLocalizationKeys.launchLive: 'Start live',
    BanayHomeLocalizationKeys.startLive: 'Go live',
    BanayHomeLocalizationKeys.noMoreProducts: 'No more products',
    BanayHomeLocalizationKeys.followedMemberFallback: 'BANAY member',
    BanayHomeLocalizationKeys.followedSubtitleFallback: 'Following',
    BanayHomeLocalizationKeys.followedSellerBadge: 'Shop',
    BanayHomeLocalizationKeys.followedProfileBadge: 'Profile',
    BanayHomeLocalizationKeys.followedLiveNow: 'Live now',
    BanayHomeLocalizationKeys.followedViewLive: 'Watch live',
    BanayHomeLocalizationKeys.followedViewProfile: 'View profile',
    BanayHomeLocalizationKeys.storiesCreateLabel: 'Create a story',
    BanayHomeLocalizationKeys.storiesYourStory: 'Your story',
    BanayHomeLocalizationKeys.storyCreateTitle: 'New story',
    BanayHomeLocalizationKeys.storyCreateSubtitle:
        'Share a photo or a video with your contacts for 24 h.',
    BanayHomeLocalizationKeys.storyPickGallery: 'Choose a photo',
    BanayHomeLocalizationKeys.storyPickGallerySubtitle: 'From your gallery',
    BanayHomeLocalizationKeys.storyPickCamera: 'Take a photo',
    BanayHomeLocalizationKeys.storyPickCameraSubtitle: 'With the camera',
    BanayHomeLocalizationKeys.storyCaptionHint: 'Add a caption…',
    BanayHomeLocalizationKeys.storyPublishAction: 'Share story',
    BanayHomeLocalizationKeys.storyPublished: 'Your story has been shared.',
    BanayHomeLocalizationKeys.storyPublishFailed: 'Unable to share the story.',
    BanayHomeLocalizationKeys.storyImagePickFailed: 'Unable to load the photo.',
    BanayHomeLocalizationKeys.storyDeleteAction: 'Delete',
    BanayHomeLocalizationKeys.storyDeleteConfirmTitle: 'Delete this story?',
    BanayHomeLocalizationKeys.storyDeleteConfirmBody:
        'Your followers will no longer see it.',
    BanayHomeLocalizationKeys.storyDeleted: 'Story deleted.',
    BanayHomeLocalizationKeys.storyDeleteFailed: 'Unable to delete the story.',
    BanayHomeLocalizationKeys.storyViewersTitle: 'Story views',
    BanayHomeLocalizationKeys.storyNoViewersYet:
        'Nobody has seen this story yet.',
    BanayHomeLocalizationKeys.storyUnavailable:
        'This story is no longer available.',
    BanayHomeLocalizationKeys.storyJustNow: 'Just now',
    BanayHomeLocalizationKeys.storyMinutesAgo: '{count} min ago',
    BanayHomeLocalizationKeys.storyHoursAgo: '{count} h ago',
    BanayHomeLocalizationKeys.storyPickVideoGallery: 'Choose a video',
    BanayHomeLocalizationKeys.storyPickVideoCamera: 'Record a video',
    BanayHomeLocalizationKeys.storyVideoTooLong:
        'The video must not exceed {seconds} s.',
    BanayHomeLocalizationKeys.storyVideoTooLarge:
        'The video must not exceed {size} MB.',
    BanayHomeLocalizationKeys.storyVideoPreviewFailed:
        'Unable to play this video.',
    BanayHomeLocalizationKeys.storyUploading: 'Sending your story…',
    BanayHomeLocalizationKeys.storyFinalizing: 'Finalizing…',
  },
  'fr': {
    BanayHomeLocalizationKeys.defaultStoreName: 'Boutique BANAY',
    BanayHomeLocalizationKeys.liveUnavailable:
        'Ce live n\'est plus disponible.',
    BanayHomeLocalizationKeys.followedTitle: 'Abonnements',
    BanayHomeLocalizationKeys.followedEmptyTitle:
        'Aucun abonnement pour le moment',
    BanayHomeLocalizationKeys.followedEmptyMessage:
        'Abonnez-vous à des boutiques ou à des personnes pour les retrouver ici.',
    BanayHomeLocalizationKeys.notificationsTooltip: 'Ouvrir les notifications',
    BanayHomeLocalizationKeys.livekitConfigIncomplete:
        'La configuration LiveKit du serveur est incomplete.',
    BanayHomeLocalizationKeys.cannotStartLive:
        'Impossible de demarrer le live pour le moment.',
    BanayHomeLocalizationKeys.liveDefaultTitle: '{name} en direct',
    BanayHomeLocalizationKeys.liveDefaultCategory: 'Presentation produit',
    BanayHomeLocalizationKeys.createLiveTitle: 'Creer un live',
    BanayHomeLocalizationKeys.createLiveSubtitle:
        'Prepare ton direct et rends-le visible tout de suite.',
    BanayHomeLocalizationKeys.liveTitleHint: 'Titre du live',
    BanayHomeLocalizationKeys.liveCategoryHint: 'Theme ou categorie',
    BanayHomeLocalizationKeys.liveTitleRequired:
        'Ajoute un titre pour lancer le live.',
    BanayHomeLocalizationKeys.liveCategoryRequired:
        'Ajoute une categorie pour lancer le live.',
    BanayHomeLocalizationKeys.launchLive: 'Lancer le live',
    BanayHomeLocalizationKeys.startLive: 'Lancer un live',
    BanayHomeLocalizationKeys.noMoreProducts: 'Plus de produits',
    BanayHomeLocalizationKeys.followedMemberFallback: 'Membre BANAY',
    BanayHomeLocalizationKeys.followedSubtitleFallback: 'Abonne',
    BanayHomeLocalizationKeys.followedSellerBadge: 'Boutique',
    BanayHomeLocalizationKeys.followedProfileBadge: 'Profil',
    BanayHomeLocalizationKeys.followedLiveNow: 'En direct maintenant',
    BanayHomeLocalizationKeys.followedViewLive: 'Voir le live',
    BanayHomeLocalizationKeys.followedViewProfile: 'Voir le profil',
    BanayHomeLocalizationKeys.storiesCreateLabel: 'Créer une story',
    BanayHomeLocalizationKeys.storiesYourStory: 'Votre story',
    BanayHomeLocalizationKeys.storyCreateTitle: 'Nouvelle story',
    BanayHomeLocalizationKeys.storyCreateSubtitle:
        'Partagez une photo ou une vidéo avec vos contacts pendant 24 h.',
    BanayHomeLocalizationKeys.storyPickGallery: 'Choisir une photo',
    BanayHomeLocalizationKeys.storyPickGallerySubtitle: 'Depuis votre galerie',
    BanayHomeLocalizationKeys.storyPickCamera: 'Prendre une photo',
    BanayHomeLocalizationKeys.storyPickCameraSubtitle: 'Avec l\'appareil photo',
    BanayHomeLocalizationKeys.storyCaptionHint: 'Ajouter une légende…',
    BanayHomeLocalizationKeys.storyPublishAction: 'Publier la story',
    BanayHomeLocalizationKeys.storyPublished: 'Votre story a été publiée.',
    BanayHomeLocalizationKeys.storyPublishFailed:
        'Impossible de publier la story.',
    BanayHomeLocalizationKeys.storyImagePickFailed:
        'Impossible de récupérer la photo.',
    BanayHomeLocalizationKeys.storyDeleteAction: 'Supprimer',
    BanayHomeLocalizationKeys.storyDeleteConfirmTitle:
        'Supprimer cette story ?',
    BanayHomeLocalizationKeys.storyDeleteConfirmBody:
        'Elle ne sera plus visible par vos abonnés.',
    BanayHomeLocalizationKeys.storyDeleted: 'Story supprimée.',
    BanayHomeLocalizationKeys.storyDeleteFailed:
        'Impossible de supprimer la story.',
    BanayHomeLocalizationKeys.storyViewersTitle: 'Vues de la story',
    BanayHomeLocalizationKeys.storyNoViewersYet:
        'Personne n\'a encore vu cette story.',
    BanayHomeLocalizationKeys.storyUnavailable:
        'Cette story n\'est plus disponible.',
    BanayHomeLocalizationKeys.storyJustNow: 'À l\'instant',
    BanayHomeLocalizationKeys.storyMinutesAgo: 'Il y a {count} min',
    BanayHomeLocalizationKeys.storyHoursAgo: 'Il y a {count} h',
    BanayHomeLocalizationKeys.storyPickVideoGallery: 'Choisir une vidéo',
    BanayHomeLocalizationKeys.storyPickVideoCamera: 'Filmer une vidéo',
    BanayHomeLocalizationKeys.storyVideoTooLong:
        'La vidéo ne doit pas dépasser {seconds} s.',
    BanayHomeLocalizationKeys.storyVideoTooLarge:
        'La vidéo ne doit pas dépasser {size} Mo.',
    BanayHomeLocalizationKeys.storyVideoPreviewFailed:
        'Impossible de lire cette vidéo.',
    BanayHomeLocalizationKeys.storyUploading: 'Envoi de la story…',
    BanayHomeLocalizationKeys.storyFinalizing: 'Finalisation en cours…',
  },
  'zh': {
    BanayHomeLocalizationKeys.defaultStoreName: 'BANAY 店铺',
    BanayHomeLocalizationKeys.liveUnavailable: '该直播已不可用。',
    BanayHomeLocalizationKeys.followedTitle: '你的关注',
    BanayHomeLocalizationKeys.followedEmptyTitle: '暂时没有关注',
    BanayHomeLocalizationKeys.followedEmptyMessage: '关注店铺或用户后会显示在这里。',
    BanayHomeLocalizationKeys.notificationsTooltip: '打开通知',
    BanayHomeLocalizationKeys.livekitConfigIncomplete: '服务器的 LiveKit 配置不完整。',
    BanayHomeLocalizationKeys.cannotStartLive: '暂时无法开始直播。',
    BanayHomeLocalizationKeys.liveDefaultTitle: '{name} 正在直播',
    BanayHomeLocalizationKeys.liveDefaultCategory: '产品展示',
    BanayHomeLocalizationKeys.createLiveTitle: '创建直播',
    BanayHomeLocalizationKeys.createLiveSubtitle: '准备你的直播并立即展示。',
    BanayHomeLocalizationKeys.liveTitleHint: '直播标题',
    BanayHomeLocalizationKeys.liveCategoryHint: '主题或分类',
    BanayHomeLocalizationKeys.liveTitleRequired: '请添加直播标题。',
    BanayHomeLocalizationKeys.liveCategoryRequired: '请添加直播分类。',
    BanayHomeLocalizationKeys.launchLive: '开始直播',
    BanayHomeLocalizationKeys.startLive: '发起直播',
    BanayHomeLocalizationKeys.noMoreProducts: '没有更多商品了',
    BanayHomeLocalizationKeys.followedMemberFallback: 'BANAY 成员',
    BanayHomeLocalizationKeys.followedSubtitleFallback: '已关注',
    BanayHomeLocalizationKeys.followedSellerBadge: '店铺',
    BanayHomeLocalizationKeys.followedProfileBadge: '资料',
    BanayHomeLocalizationKeys.followedLiveNow: '正在直播',
    BanayHomeLocalizationKeys.followedViewLive: '观看直播',
    BanayHomeLocalizationKeys.followedViewProfile: '查看资料',
    BanayHomeLocalizationKeys.storiesCreateLabel: '创建动态',
    BanayHomeLocalizationKeys.storiesYourStory: '我的动态',
    BanayHomeLocalizationKeys.storyCreateTitle: '新动态',
    BanayHomeLocalizationKeys.storyCreateSubtitle: '与联系人分享一张照片或一段视频，保留 24 小时。',
    BanayHomeLocalizationKeys.storyPickGallery: '选择照片',
    BanayHomeLocalizationKeys.storyPickGallerySubtitle: '从相册中选择',
    BanayHomeLocalizationKeys.storyPickCamera: '拍照',
    BanayHomeLocalizationKeys.storyPickCameraSubtitle: '使用相机',
    BanayHomeLocalizationKeys.storyCaptionHint: '添加文字…',
    BanayHomeLocalizationKeys.storyPublishAction: '发布动态',
    BanayHomeLocalizationKeys.storyPublished: '动态已发布。',
    BanayHomeLocalizationKeys.storyPublishFailed: '无法发布动态。',
    BanayHomeLocalizationKeys.storyImagePickFailed: '无法获取照片。',
    BanayHomeLocalizationKeys.storyDeleteAction: '删除',
    BanayHomeLocalizationKeys.storyDeleteConfirmTitle: '删除这条动态？',
    BanayHomeLocalizationKeys.storyDeleteConfirmBody: '关注者将无法再看到它。',
    BanayHomeLocalizationKeys.storyDeleted: '动态已删除。',
    BanayHomeLocalizationKeys.storyDeleteFailed: '无法删除动态。',
    BanayHomeLocalizationKeys.storyViewersTitle: '动态浏览',
    BanayHomeLocalizationKeys.storyNoViewersYet: '还没有人看过这条动态。',
    BanayHomeLocalizationKeys.storyUnavailable: '该动态已不可用。',
    BanayHomeLocalizationKeys.storyJustNow: '刚刚',
    BanayHomeLocalizationKeys.storyMinutesAgo: '{count} 分钟前',
    BanayHomeLocalizationKeys.storyHoursAgo: '{count} 小时前',
    BanayHomeLocalizationKeys.storyPickVideoGallery: '选择视频',
    BanayHomeLocalizationKeys.storyPickVideoCamera: '拍摄视频',
    BanayHomeLocalizationKeys.storyVideoTooLong: '视频不能超过 {seconds} 秒。',
    BanayHomeLocalizationKeys.storyVideoTooLarge: '视频不能超过 {size} MB。',
    BanayHomeLocalizationKeys.storyVideoPreviewFailed: '无法播放该视频。',
    BanayHomeLocalizationKeys.storyUploading: '正在发送动态…',
    BanayHomeLocalizationKeys.storyFinalizing: '正在完成…',
  },
  'hi': {
    BanayHomeLocalizationKeys.defaultStoreName: 'BANAY दुकान',
    BanayHomeLocalizationKeys.liveUnavailable: 'यह लाइव अब उपलब्ध नहीं है।',
    BanayHomeLocalizationKeys.followedTitle: 'आपकी फॉलोइंग',
    BanayHomeLocalizationKeys.followedEmptyTitle: 'अभी कोई सदस्यता नहीं',
    BanayHomeLocalizationKeys.followedEmptyMessage:
        'दुकानों या लोगों को फॉलो करें ताकि वे यहां दिखें।',
    BanayHomeLocalizationKeys.notificationsTooltip: 'सूचनाएं खोलें',
    BanayHomeLocalizationKeys.livekitConfigIncomplete:
        'सर्वर की LiveKit कॉन्फ़िगरेशन अधूरी है।',
    BanayHomeLocalizationKeys.cannotStartLive:
        'अभी लाइव शुरू नहीं किया जा सकता।',
    BanayHomeLocalizationKeys.liveDefaultTitle: '{name} लाइव है',
    BanayHomeLocalizationKeys.liveDefaultCategory: 'प्रोडक्ट प्रस्तुति',
    BanayHomeLocalizationKeys.createLiveTitle: 'लाइव बनाएं',
    BanayHomeLocalizationKeys.createLiveSubtitle:
        'अपना लाइव तैयार करें और तुरंत दिखाएं।',
    BanayHomeLocalizationKeys.liveTitleHint: 'लाइव शीर्षक',
    BanayHomeLocalizationKeys.liveCategoryHint: 'थीम या श्रेणी',
    BanayHomeLocalizationKeys.liveTitleRequired:
        'लाइव शुरू करने के लिए शीर्षक जोड़ें।',
    BanayHomeLocalizationKeys.liveCategoryRequired:
        'लाइव शुरू करने के लिए श्रेणी जोड़ें।',
    BanayHomeLocalizationKeys.launchLive: 'लाइव शुरू करें',
    BanayHomeLocalizationKeys.startLive: 'एक लाइव शुरू करें',
    BanayHomeLocalizationKeys.noMoreProducts: 'और उत्पाद नहीं हैं',
    BanayHomeLocalizationKeys.followedMemberFallback: 'BANAY सदस्य',
    BanayHomeLocalizationKeys.followedSubtitleFallback: 'फॉलो किया गया',
    BanayHomeLocalizationKeys.followedSellerBadge: 'दुकान',
    BanayHomeLocalizationKeys.followedProfileBadge: 'प्रोफ़ाइल',
    BanayHomeLocalizationKeys.followedLiveNow: 'अभी लाइव',
    BanayHomeLocalizationKeys.followedViewLive: 'लाइव देखें',
    BanayHomeLocalizationKeys.followedViewProfile: 'प्रोफ़ाइल देखें',
    BanayHomeLocalizationKeys.storiesCreateLabel: 'स्टोरी बनाएं',
    BanayHomeLocalizationKeys.storiesYourStory: 'आपकी स्टोरी',
    BanayHomeLocalizationKeys.storyCreateTitle: 'नई स्टोरी',
    BanayHomeLocalizationKeys.storyCreateSubtitle:
        'अपने संपर्कों के साथ 24 घंटे के लिए एक फोटो या वीडियो साझा करें।',
    BanayHomeLocalizationKeys.storyPickGallery: 'फोटो चुनें',
    BanayHomeLocalizationKeys.storyPickGallerySubtitle: 'अपनी गैलरी से',
    BanayHomeLocalizationKeys.storyPickCamera: 'फोटो लें',
    BanayHomeLocalizationKeys.storyPickCameraSubtitle: 'कैमरे से',
    BanayHomeLocalizationKeys.storyCaptionHint: 'कैप्शन जोड़ें…',
    BanayHomeLocalizationKeys.storyPublishAction: 'स्टोरी साझा करें',
    BanayHomeLocalizationKeys.storyPublished: 'आपकी स्टोरी साझा हो गई।',
    BanayHomeLocalizationKeys.storyPublishFailed: 'स्टोरी साझा नहीं हो सकी।',
    BanayHomeLocalizationKeys.storyImagePickFailed: 'फोटो लोड नहीं हो सकी।',
    BanayHomeLocalizationKeys.storyDeleteAction: 'हटाएं',
    BanayHomeLocalizationKeys.storyDeleteConfirmTitle: 'यह स्टोरी हटाएं?',
    BanayHomeLocalizationKeys.storyDeleteConfirmBody:
        'आपके फॉलोअर्स इसे अब नहीं देख पाएंगे।',
    BanayHomeLocalizationKeys.storyDeleted: 'स्टोरी हटा दी गई।',
    BanayHomeLocalizationKeys.storyDeleteFailed: 'स्टोरी हटाई नहीं जा सकी।',
    BanayHomeLocalizationKeys.storyViewersTitle: 'स्टोरी व्यूज़',
    BanayHomeLocalizationKeys.storyNoViewersYet:
        'इस स्टोरी को अभी तक किसी ने नहीं देखा।',
    BanayHomeLocalizationKeys.storyUnavailable: 'यह स्टोरी अब उपलब्ध नहीं है।',
    BanayHomeLocalizationKeys.storyJustNow: 'अभी-अभी',
    BanayHomeLocalizationKeys.storyMinutesAgo: '{count} मिनट पहले',
    BanayHomeLocalizationKeys.storyHoursAgo: '{count} घंटे पहले',
    BanayHomeLocalizationKeys.storyPickVideoGallery: 'वीडियो चुनें',
    BanayHomeLocalizationKeys.storyPickVideoCamera: 'वीडियो रिकॉर्ड करें',
    BanayHomeLocalizationKeys.storyVideoTooLong:
        'वीडियो {seconds} सेकंड से अधिक नहीं होना चाहिए।',
    BanayHomeLocalizationKeys.storyVideoTooLarge:
        'वीडियो {size} MB से अधिक नहीं होना चाहिए।',
    BanayHomeLocalizationKeys.storyVideoPreviewFailed:
        'यह वीडियो चलाया नहीं जा सका।',
    BanayHomeLocalizationKeys.storyUploading: 'स्टोरी भेजी जा रही है…',
    BanayHomeLocalizationKeys.storyFinalizing: 'अंतिम रूप दिया जा रहा है…',
  },
  'es': {
    BanayHomeLocalizationKeys.defaultStoreName: 'Tienda BANAY',
    BanayHomeLocalizationKeys.liveUnavailable:
        'Este live ya no esta disponible.',
    BanayHomeLocalizationKeys.followedTitle: 'Tus suscripciones',
    BanayHomeLocalizationKeys.followedEmptyTitle: 'Aun no hay suscripciones',
    BanayHomeLocalizationKeys.followedEmptyMessage:
        'Sigue tiendas o personas para encontrarlas aquí.',
    BanayHomeLocalizationKeys.notificationsTooltip: 'Abrir notificaciones',
    BanayHomeLocalizationKeys.livekitConfigIncomplete:
        'La configuracion LiveKit del servidor esta incompleta.',
    BanayHomeLocalizationKeys.cannotStartLive:
        'No se puede iniciar el live por ahora.',
    BanayHomeLocalizationKeys.liveDefaultTitle: '{name} en vivo',
    BanayHomeLocalizationKeys.liveDefaultCategory: 'Presentacion de producto',
    BanayHomeLocalizationKeys.createLiveTitle: 'Crear un live',
    BanayHomeLocalizationKeys.createLiveSubtitle:
        'Prepara tu directo y hazlo visible de inmediato.',
    BanayHomeLocalizationKeys.liveTitleHint: 'Titulo del live',
    BanayHomeLocalizationKeys.liveCategoryHint: 'Tema o categoria',
    BanayHomeLocalizationKeys.liveTitleRequired:
        'Agrega un titulo para iniciar el live.',
    BanayHomeLocalizationKeys.liveCategoryRequired:
        'Agrega una categoria para iniciar el live.',
    BanayHomeLocalizationKeys.launchLive: 'Iniciar live',
    BanayHomeLocalizationKeys.startLive: 'Lanzar un live',
    BanayHomeLocalizationKeys.noMoreProducts: 'No hay mas productos',
    BanayHomeLocalizationKeys.followedMemberFallback: 'Miembro BANAY',
    BanayHomeLocalizationKeys.followedSubtitleFallback: 'Seguido',
    BanayHomeLocalizationKeys.followedSellerBadge: 'Tienda',
    BanayHomeLocalizationKeys.followedProfileBadge: 'Perfil',
    BanayHomeLocalizationKeys.followedLiveNow: 'En vivo ahora',
    BanayHomeLocalizationKeys.followedViewLive: 'Ver live',
    BanayHomeLocalizationKeys.followedViewProfile: 'Ver perfil',
    BanayHomeLocalizationKeys.storiesCreateLabel: 'Crear una historia',
    BanayHomeLocalizationKeys.storiesYourStory: 'Tu historia',
    BanayHomeLocalizationKeys.storyCreateTitle: 'Nueva historia',
    BanayHomeLocalizationKeys.storyCreateSubtitle:
        'Comparte una foto o un vídeo con tus contactos durante 24 h.',
    BanayHomeLocalizationKeys.storyPickGallery: 'Elegir una foto',
    BanayHomeLocalizationKeys.storyPickGallerySubtitle: 'Desde tu galería',
    BanayHomeLocalizationKeys.storyPickCamera: 'Tomar una foto',
    BanayHomeLocalizationKeys.storyPickCameraSubtitle: 'Con la cámara',
    BanayHomeLocalizationKeys.storyCaptionHint: 'Añadir un texto…',
    BanayHomeLocalizationKeys.storyPublishAction: 'Publicar la historia',
    BanayHomeLocalizationKeys.storyPublished: 'Tu historia se ha publicado.',
    BanayHomeLocalizationKeys.storyPublishFailed:
        'No se pudo publicar la historia.',
    BanayHomeLocalizationKeys.storyImagePickFailed:
        'No se pudo cargar la foto.',
    BanayHomeLocalizationKeys.storyDeleteAction: 'Eliminar',
    BanayHomeLocalizationKeys.storyDeleteConfirmTitle:
        '¿Eliminar esta historia?',
    BanayHomeLocalizationKeys.storyDeleteConfirmBody:
        'Tus seguidores ya no la verán.',
    BanayHomeLocalizationKeys.storyDeleted: 'Historia eliminada.',
    BanayHomeLocalizationKeys.storyDeleteFailed:
        'No se pudo eliminar la historia.',
    BanayHomeLocalizationKeys.storyViewersTitle: 'Vistas de la historia',
    BanayHomeLocalizationKeys.storyNoViewersYet:
        'Nadie ha visto esta historia todavía.',
    BanayHomeLocalizationKeys.storyUnavailable:
        'Esta historia ya no está disponible.',
    BanayHomeLocalizationKeys.storyJustNow: 'Justo ahora',
    BanayHomeLocalizationKeys.storyMinutesAgo: 'Hace {count} min',
    BanayHomeLocalizationKeys.storyHoursAgo: 'Hace {count} h',
    BanayHomeLocalizationKeys.storyPickVideoGallery: 'Elegir un vídeo',
    BanayHomeLocalizationKeys.storyPickVideoCamera: 'Grabar un vídeo',
    BanayHomeLocalizationKeys.storyVideoTooLong:
        'El vídeo no debe superar {seconds} s.',
    BanayHomeLocalizationKeys.storyVideoTooLarge:
        'El vídeo no debe superar {size} MB.',
    BanayHomeLocalizationKeys.storyVideoPreviewFailed:
        'No se pudo reproducir este vídeo.',
    BanayHomeLocalizationKeys.storyUploading: 'Enviando tu historia…',
    BanayHomeLocalizationKeys.storyFinalizing: 'Finalizando…',
  },
  'ar': {
    BanayHomeLocalizationKeys.defaultStoreName: 'متجر BANAY',
    BanayHomeLocalizationKeys.liveUnavailable: 'هذا البث لم يعد متاحا.',
    BanayHomeLocalizationKeys.followedTitle: 'متابعاتك',
    BanayHomeLocalizationKeys.followedEmptyTitle: 'لا توجد متابعات حاليا',
    BanayHomeLocalizationKeys.followedEmptyMessage:
        'تابع المتاجر أو الأشخاص لتجدهم هنا.',
    BanayHomeLocalizationKeys.notificationsTooltip: 'افتح الإشعارات',
    BanayHomeLocalizationKeys.livekitConfigIncomplete:
        'إعداد LiveKit على الخادم غير مكتمل.',
    BanayHomeLocalizationKeys.cannotStartLive: 'لا يمكن بدء البث حاليا.',
    BanayHomeLocalizationKeys.liveDefaultTitle: '{name} على المباشر',
    BanayHomeLocalizationKeys.liveDefaultCategory: 'عرض منتج',
    BanayHomeLocalizationKeys.createLiveTitle: 'إنشاء بث مباشر',
    BanayHomeLocalizationKeys.createLiveSubtitle:
        'جهز البث واجعله مرئيا على الفور.',
    BanayHomeLocalizationKeys.liveTitleHint: 'عنوان البث',
    BanayHomeLocalizationKeys.liveCategoryHint: 'الموضوع أو الفئة',
    BanayHomeLocalizationKeys.liveTitleRequired: 'أضف عنوانا لبدء البث.',
    BanayHomeLocalizationKeys.liveCategoryRequired: 'أضف فئة لبدء البث.',
    BanayHomeLocalizationKeys.launchLive: 'ابدأ البث',
    BanayHomeLocalizationKeys.startLive: 'إطلاق بث مباشر',
    BanayHomeLocalizationKeys.noMoreProducts: 'لا توجد منتجات أخرى',
    BanayHomeLocalizationKeys.followedMemberFallback: 'عضو BANAY',
    BanayHomeLocalizationKeys.followedSubtitleFallback: 'متابَع',
    BanayHomeLocalizationKeys.followedSellerBadge: 'متجر',
    BanayHomeLocalizationKeys.followedProfileBadge: 'الملف الشخصي',
    BanayHomeLocalizationKeys.followedLiveNow: 'مباشر الآن',
    BanayHomeLocalizationKeys.followedViewLive: 'شاهد البث',
    BanayHomeLocalizationKeys.followedViewProfile: 'شاهد الملف',
    BanayHomeLocalizationKeys.storiesCreateLabel: 'إنشاء قصة',
    BanayHomeLocalizationKeys.storiesYourStory: 'قصتك',
    BanayHomeLocalizationKeys.storyCreateTitle: 'قصة جديدة',
    BanayHomeLocalizationKeys.storyCreateSubtitle:
        'شارك صورة أو فيديو مع جهات اتصالك لمدة 24 ساعة.',
    BanayHomeLocalizationKeys.storyPickGallery: 'اختيار صورة',
    BanayHomeLocalizationKeys.storyPickGallerySubtitle: 'من معرض الصور',
    BanayHomeLocalizationKeys.storyPickCamera: 'التقاط صورة',
    BanayHomeLocalizationKeys.storyPickCameraSubtitle: 'باستخدام الكاميرا',
    BanayHomeLocalizationKeys.storyCaptionHint: 'أضف تعليقًا…',
    BanayHomeLocalizationKeys.storyPublishAction: 'نشر القصة',
    BanayHomeLocalizationKeys.storyPublished: 'تم نشر قصتك.',
    BanayHomeLocalizationKeys.storyPublishFailed: 'تعذر نشر القصة.',
    BanayHomeLocalizationKeys.storyImagePickFailed: 'تعذر تحميل الصورة.',
    BanayHomeLocalizationKeys.storyDeleteAction: 'حذف',
    BanayHomeLocalizationKeys.storyDeleteConfirmTitle: 'حذف هذه القصة؟',
    BanayHomeLocalizationKeys.storyDeleteConfirmBody:
        'لن يراها متابعوك بعد الآن.',
    BanayHomeLocalizationKeys.storyDeleted: 'تم حذف القصة.',
    BanayHomeLocalizationKeys.storyDeleteFailed: 'تعذر حذف القصة.',
    BanayHomeLocalizationKeys.storyViewersTitle: 'مشاهدات القصة',
    BanayHomeLocalizationKeys.storyNoViewersYet: 'لم يشاهد أحد هذه القصة بعد.',
    BanayHomeLocalizationKeys.storyUnavailable: 'هذه القصة لم تعد متاحة.',
    BanayHomeLocalizationKeys.storyJustNow: 'الآن',
    BanayHomeLocalizationKeys.storyMinutesAgo: 'قبل {count} دقيقة',
    BanayHomeLocalizationKeys.storyHoursAgo: 'قبل {count} ساعة',
    BanayHomeLocalizationKeys.storyPickVideoGallery: 'اختيار فيديو',
    BanayHomeLocalizationKeys.storyPickVideoCamera: 'تصوير فيديو',
    BanayHomeLocalizationKeys.storyVideoTooLong:
        'يجب ألا يتجاوز الفيديو {seconds} ثانية.',
    BanayHomeLocalizationKeys.storyVideoTooLarge:
        'يجب ألا يتجاوز الفيديو {size} ميغابايت.',
    BanayHomeLocalizationKeys.storyVideoPreviewFailed:
        'تعذر تشغيل هذا الفيديو.',
    BanayHomeLocalizationKeys.storyUploading: 'جارٍ إرسال قصتك…',
    BanayHomeLocalizationKeys.storyFinalizing: 'جارٍ الإنهاء…',
  },
};
